spring.datasource.url=jdbc:postgresql://dpg-d9lhmi95efls73bbb6kg-a.singapore-postgres.render.com:5432/fooddelivery_wim0
spring.datasource.username=fooddelivery_wim0_user
spring.datasource.password=1IoLatUA4Jemwc3RGeZKtZbxKazONELr

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8081}